spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:auth_service}
    username: ${DB_USERNAME:auth_user}
    password: ${DB_PASSWORD:auth_password}
  jpa:
    show-sql: false
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**
    livereload:
      enabled: true
      port: 35729
    add-properties: false

logging:
  level:
    com.example.authservice: DEBUG

