package com.example.authservice.common.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    BAD_REQUEST,
    UNAUTHORIZED,
    FORBIDDEN,
    NOT_FOUND,
    INVALID_CREDENTIALS,
    EMAIL_ALREADY_EXISTS,
    INVALID_TOKEN,
    REFRESH_TOKEN_INVALID,
    REFRESH_TOKEN_EXPIRED,
    REFRESH_TOKEN_REVOKED,
    SESSION_NOT_FOUND,
    SESSION_NOT_OWNED,
    USER_NOT_FOUND,
    EMAIL_ALREADY_VERIFIED,
    INTERNAL_ERROR
}
