package com.example.authservice.audit.entity;

public enum AuditEventType {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    REFRESH_SUCCESS,
    REFRESH_FAILED,
    REGISTER_SUCCESS,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    EMAIL_VERIFIED,
    LOGOUT,
    FORGOT_PASSWORD_REQUESTED
}
